### ISSUE TITLE
Send Welcome email

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-backend#42]
**Acceptance Criteria**
After a user has successfully confirmed their email, a "Welcome" email should be sent to the user

```
GIVEN I registered an account

AND I navigate to my email and open the "Confirm email" email

AND I click on the `Confirm email` button

AND I am redirected to the Dots log in page so that I can log in.

THEN once I successfully log in for the first time I am sent a "Welcome" email to the email provided during registration so that I can have an easy way to navigate back to the Dots app by checking my email.

```

**Additional context**
Email template is here:
[Welcome email_Dots.html.zip](https://github.com/hikaya-io/dots-backend/files/4589699/Welcome.email_Dots.html.zip)

**Comment by sannleen** [comment]
Fixed: 
<img width="964" alt="image" src="https://user-images.githubusercontent.com/16039248/84927055-f77de600-b0d4-11ea-8c8f-4f37f394517c.png">
