### ISSUE TITLE
Workspace model changes

### ISSUE THREAD

**Issue by nasirhjafri** [hikaya-io/dots-backend#49]
Rename fields to match the FE.

Rename `is_default` field to `is_current`
Rename `name` field to `display_name`
Rename `slug` field to `name`
Rename `url` fiel to `website`
Add `email` field - required.

@michaelbukachi @andrewtpham Does it make sense?

**Comment by andrewtpham** [comment]
This list looks good. I would make email not required since we wont use this information for any way of contacting for now (We'll use Owner as main point of contact).
