### ISSUE TITLE
Ability to enter email or username including support for no case sensitivity

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-backend#53]
**Current behavior**
Currently we support login using a username but not email. In addition the username is case sensitive.

**Expected behavior**
We would like to support the use of email AND username
AND the ability to enter an email OR username without case sensitivity (Test@gmail.com OR test@gmail.com AND username=test OR username=Test)

This is related to the FE issue: https://github.com/hikaya-io/dots-frontend/issues/80

**Comment by sannleen** [comment]
Implemented
